set(BUILD_SHARED_LIBS               OFF)
set(BUILD_UTILS                     OFF)
set(GLFW_BUILD_DOCS                 OFF)
set(GLFW_INSTALL                    OFF)
set(USE_MSVC_RUNTIME_LIBRARY_DLL    OFF)